### ISSUE TITLE
add support for gremlin 3.5.0

### ISSUE THREAD

**Issue by talr1** [shutterstock/gremlin-aws-sigv4#21]
current gremlin package is 3.4.8 (3.4.9, 3.4.10, 3.4.11)
latest package is 3.5.0

Thanks

**Comment by fabrice404** [comment]
HI, I've released a new version compatible with the 3.5.1.
https://www.npmjs.com/package/gremlin-aws-sigv4

**Comment by talr1** [comment]
Thank You
