### ISSUE TITLE
Gremlin 3.6.1 breaks the package

### ISSUE THREAD

**Issue by JoyfulShush** [shutterstock/gremlin-aws-sigv4#29]
Hey @fabrice404 ,

First, I would like to say the AWS wrapper works very well, thank you for that.

Unfortunately, I've noticed that since gremlin is in version 3.6.1, the package breaks. This occurs due to gremlin no longer supporting the `connectOnStartup` option for the client's connection, as it was deprecated. Instead, a manual `client.open()` is required to connect to Neptune.

There seems to be already a PR #28 that should fix this.

Can you please review it and release a new version that includes the fix?

Thanks.

**Comment by fabrice404** [comment]
Hi, yes sorry I was on PTO, I will merge and deploy today or tomorrow.

**Comment by JoyfulShush** [comment]
@fabrice404 Do you have an ETA for this? We're currently forcing Gremlin 3.6.0 since 3.6.1 and up are broken until fixed.

**Comment by fabrice404** [comment]
I haven't merged the PR last week because the original client seems not to connect automatically anymore when instantiated. 
As it's a breaking change, the library needs to warn that the `connectOnStartup` parameter is deprecated and users need to explicitly call the `open()` method. I will create a new PR in the next few days.

**Comment by JoyfulShush** [comment]
Thanks, the fix is exactly as you say, I've locally tweaked it to do exactly that and it works for me. 

The PR seems to be good for that (they call the `open()` method), not sure why you're not using that. The author of the PR just forgot to add the `await` as `open()` is an async operation.

**Comment by fabrice404** [comment]
<s>A constructor cannot be async, that's the reason I can't use the https://github.com/shutterstock/gremlin-aws-sigv4/pull/28, `open` call will need to be done after calling the constructor.</s>

Please ignore the comment, it's using callbacks, so no need for the await.

**Comment by fabrice404** [comment]
I've just created https://github.com/shutterstock/gremlin-aws-sigv4/pull/30, let me know what you think about it.

**Comment by JoyfulShush** [comment]
Done in #30
